# animation-1
- domain_lora_scale: 1.0
  adapter_lora_path: "models/DreamBooth_LoRA/v3_sd15_adapter.ckpt"
  dreambooth_path:   "models/DreamBooth_LoRA/revAnimated_v2Rebirth.safetensors"
  ipa_path: ""

  inference_config: "configs/inference/inference.yaml"
  motion_module:    "models/Motion_with_LoRA/character.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition_32.yaml"
  controlnet_path:   "models/ReferenceNet/character.ckpt"

  # seed: 42
  steps: 50
  guidance_scale: 5

  controlnet_image_indexes: [7]
  controlnet_images:
    - "data/test_frames/0"
    - "data/test_frames/1"
    - "data/test_frames/2"
    - "data/test_frames/3"
    - "data/test_frames/4"
    - "data/test_frames/5"
    - "data/test_frames/6"
    - "data/test_frames/7"
    - "data/test_frames/8"
    - "data/test_frames/9"
    - "data/test_frames/10"
    - "data/test_frames/11"
    - "data/test_frames/12"
    - "data/test_frames/13"
    - "data/test_frames/14"
    - "data/test_frames/15"
    - "data/test_frames/16"
    - "data/test_frames/17"
    - "data/test_frames/18"
    - "data/test_frames/19"
    - "data/test_frames/20"
    - "data/test_frames/21"
    - "data/test_frames/22"
    - "data/test_frames/23"
    - "data/test_frames/24"
    - "data/test_frames/25"
    - "data/test_frames/26"
    - "data/test_frames/27"
    - "data/test_frames/28"
    - "data/test_frames/29"
    - "data/test_frames/30"
    - "data/test_frames/31"
    - "data/test_frames/32"
    - "data/test_frames/33"
    - "data/test_frames/34"
    - "data/test_frames/35"
    - "data/test_frames/36"
    - "data/test_frames/37"
    - "data/test_frames/38"
    - "data/test_frames/39"
    - "data/test_frames/40"
    - "data/test_frames/41"
    - "data/test_frames/42"
    - "data/test_frames/43"
    - "data/test_frames/44"
    - "data/test_frames/45"
    - "data/test_frames/46"
    - "data/test_frames/47"
    - "data/test_frames/48"
    - "data/test_frames/49"
  controlnet_conditioning_scale: 1
  
  prompt:
    - "a lone tree on an island surrounded by water under a dramatic sky"
    - "an elephant balancing on a tree branch in a desert"
    - "a person standing by a lake with mountains in the background"
    - "a surprised cat stealing a fish at a market"
    - "a lighthouse on a rocky coast seen from a village street"
    - "a woman in a headscarf with a serene expression"
    - "a dreamy portrait of a girl in a school uniform"
    - "a girl with glasses and messy hair looking pensively"
    - "a woman with Day of the Dead makeup and flowers in her hair"
    - "a futuristic girl with neon lights and headphones"
    - "a delicate sketch of a girl with intricate details"
    - "a woman in a regal outfit with a crown"
    - "a woman in an elegant dress with jewelry"
    - "a smiling man with tousled hair"
    - "a woman with soft waves in her hair"
    - "a sketch of an old man with a long beard"
    - "a detailed model of a robotic figure"
    - "two people standing under a starry sky by a bridge"
    - "a girl in a school uniform with earphones"
    - "a character resembling a warrior duck in traditional attire"
    - "a pixelated character with blue hair and a lab coat"
    - "a man on a scooter carrying a large box"
    - "the Mona Lisa painting"
    - "Starry Night by Vincent van Gogh"
    - "a self-portrait of Vincent van Gogh"
    - "an ink painting of a running horse"
    - "a textured portrait of a woman"
    - "a countryside house with a garden path"
    - "a swan on a calm lake at sunset"
    - "a cute cartoon fox with a bow"
    - "a tabby cat with bright eyes"
    - "a cute llama with long eyelashes and a rainbow background"
    - "a stylized portrait of Batman"
    - "a colorful mosaic of a wave at sunset"
    - "sunflowers in a vase by Vincent van Gogh"
    - "a patchwork puppy with a big smile"
    - "a sketch of a woman with bold red lips"
    - "a sailboat on a sunset-lit sea"
    - "a serene scene with deer by a bridge in a forest"
    - "a silhouette of a deer in a misty forest"
    - "a man in a black jacket smiling"
    - "a minion dressed as the Girl with a Pearl Earring"
    - "a cat performing a ballet dance"
    - "a surreal landscape with swirling colors"
    - "a man in a green sweater with arms crossed"
    - "a dog looking out of an airplane window"
    - "a sunny beach with a lighthouse in the distance"
    - "a woman in a dress made of daisies"
    - "a cup of coffee by a lakeside at sunrise"
    - "a man with glasses and a friendly smile"
  n_prompt:
    - "worst quality, low quality, letterboxed"


  ddim: true
  sample_size: 512